web:
    build: .
    links:
        - mysql
    expose:
        - 80
    volumes:
        - .:/app
    labels:
        com.continuouspipe.visibility: public
        com.continuouspipe.image-name: sroze/php-example-manual
mysql:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    expose:
        - 3306
    labels:
        com.continuouspipe.update: lock
