web:
    build: .
    links:
        - mysql
    expose:
        - 80
    labels:
        com.continuouspipe.public: true
        com.continuouspipe.image-name: sroze/php-example
mysql:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    expose:
        - 3306

